version: '3.8'

services:
  gclaude-enterprise:
    build: .
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - PORT=3007
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  monitoring:
    image: gclaude-enterprise
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - MONITORING_PORT=3008
    depends_on:
      - gclaude-enterprise
    restart: unless-stopped