#!/bin/bash

echo "🚀 部署到 Render.com"
echo "請手動執行以下步驟："
echo ""
echo "1. 訪問 https://render.com"
echo "2. 登入您的帳號"
echo "3. 點擊 'New' → 'Web Service'"
echo "4. 連接 GitHub 或上傳程式碼"
echo "5. 設定以下參數："
echo ""
echo "   Name: gclaude-enterprise-system"
echo "   Environment: Node"
echo "   Build Command: npm install"
echo "   Start Command: node enterprise-server.js"
echo "   Port: 3007"
echo ""
echo "6. 環境變數設定："
echo "   NODE_ENV=production"
echo "   JWT_SECRET=gclaude-enterprise-super-secret-key-2024"
echo "   TELEGRAM_BOT_TOKEN=7659930552:AAF_jF1rAXFnjFO176-9X5fKfBwbrko8BNc"
echo "   TELEGRAM_BOSS_GROUP_ID=-1002658082392"
echo ""
echo "7. 點擊 'Create Web Service'"
echo ""
echo "✅ 部署完成後，您將獲得 .onrender.com 網址"